name: CI/CD on PR

on:
  pull_request:


jobs:
  cd-dev:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: lamb2
      docker-tag: '${{ github.sha }}'
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
